language: bash
before_install:
    - lsb_release -a
    - sudo apt-get update -qq
install:
    - sudo make dependencies
    - make local
script:
    # make test and create Debian package
    - make package
    # locally install package
    - sudo dpkg -i gndaccess_*.deb
    - sudo service gndaccess status
    # test against localhost
    - export TEST_URL=6699
    - prove -Ilib -Ilocal/lib/perl5 -v

after_failure:
    - tail -200 /var/log/gndaccess/error.log

# Release Debian package via GitHub releases on tagged commits
before_deploy:
    - export RELEASE_FILE=$(ls *.deb)
    - echo "deploying $RELEASE_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: TVPV2HwXkCKZNqZ28Xn9sTF/bdU3wEpS0kGDWp2Jc1k2fwe0JW6I8XfoFw6XeGV1iQkXbZEQnXk0X/cudav6/SIRkVA/0Q5gcrucbDwzFlUA1Q70Na4bspcUQCiaiHWehLwHKxHOfgH7OVepSd++dPAmMWquIyK9V7Rx8JvvpsI=
  file: "${RELEASE_FILE}"
  on:
    tags: true
