.TH "GNDACCESS" "1" "" "Manual" ""
.SH NAME
.PP
gndaccess \- Access GND records via HTTP
.SH SYNOPSIS
.PP
The application is automatically started as service, listening on port
6699.
.IP
.nf
\f[C]
sudo\ service\ gndaccess\ {status|start|stop|restart}
\f[]
.fi
.SH DESCRIPTION
.PP
This applications provices a web service to access GND records via HTTP
in different formats.
The format must be provided with URL query parameter \f[C]format\f[].
.IP \[bu] 2
<http://localhost:6699/4021477-1?format=aref>
.SS Supported formats
.IP \[bu] 2
\f[C]aref\f[]: aREF format (RDF in JSON for easy access, similar to
JSON\-LD)
.IP \[bu] 2
\f[C]nt\f[]: NTriples
.IP \[bu] 2
\f[C]rdfxml\f[]: RDF/XML
.IP \[bu] 2
\f[C]marcxml\f[]
.SS CORS and JSONP
.PP
Cross\-Origin Resource Sharing (CORS) is enabled by default.
In addition all JSON\-based formats can can be returned in JSONP with
parameter \f[C]callback\f[]:
.IP \[bu] 2
<http://localhost:6699/4021477-1?format=aref&callback=abc>
.SS HTML client
.PP
The application includes an HTML client, consisting of the following
files:
.IP \[bu] 2
\f[C]index.html\f[]
.IP \[bu] 2
\f[C]gndaccess.css\f[]
.IP \[bu] 2
\f[C]gndaccess.json\f[]
.IP \[bu] 2
\f[C]formats.json\f[] (generated dynamically)
.SH INSTALLATION
.PP
The application is packaged as Debian package.
Releases can be found at
.IP \[bu] 2
<https://github.com/gbv/gndaccess/releases>
.PP
No binaries are included, so the package should work on all
architectures.
It is tested with Ubuntu 12.04 LTS and Ubuntu 14.04 LTS.
.PP
Files are installed at the following locations:
.IP \[bu] 2
\f[C]/srv/gndaccess/\f[] \- application
.IP \[bu] 2
\f[C]/var/log/gndaccess/\f[] \- log files \f[C]access.log\f[] and
\f[C]error.log\f[]
.IP \[bu] 2
\f[C]/etc/logrotate.d/gndaccess\f[] \- logrotate configuration (compress
daily, keep 14 days)
.IP \[bu] 2
\f[C]/etc/default/gndaccess\f[] \- server configuration
.IP \[bu] 2
\f[C]/etc/gndaccess/\f[] \- application configuration
.SH CONFIGURATION
.PP
See \f[C]/etc/default/gndaccess\f[] for basic configuration.
Settings are not modified by updates.
Only simple key value\-pairs are allowed with the following keys:
.IP \[bu] 2
\f[C]PORT\f[] \- port number (required, 6699 by default)
.IP \[bu] 2
\f[C]WORKERS\f[] \- number of parallel connections (required, 5 by
default).
If put behind a HTTP proxy, this number is not affected by slow cient
connections but only by the time of processing each request.
.IP \[bu] 2
\f[C]PROXY\f[] \- a space\-or\-comma\-separated list of trusted IPs or
IP\-ranges (e.g.
\f[C]192.168.0.0/16\f[]) to take from the \f[C]X\-Forwarded\-For\f[]
header.
The special value \f[C]*\f[] can be used to trust all IPs.
.PP
Restart is needed after changes.
.PP
The HTML client can be customized by putting static files into directory
\f[C]/etc/gndaccess/htdocs\f[] to override files in
\f[C]/srv/gndaccess/htdocs\f[].
.SH SEE ALSO
.PP
Changelog is located in file
\f[C]debian/changelog\f[] (debian/changelog) in the source code
repository.
.PP
Source code and issue tracker at <https://github.com/gbv/gndaccess>.
See file \f[C]CONTRIBUTING.md\f[] source code organization.
.PP
See <http://www.dnb.de/entityfacts> for a similar service.
